# Auth - signup + token

###
# Creer un compte
POST {{supabaseUrl}}/auth/v1/signup
Content-Type: application/json
apikey: {{supabaseKey}}

{
  "email": "test@cloudbreak.app",
  "password": "motdepasse123"
}

###
# Se connecter et recuperer access_token dans la reponse
POST {{supabaseUrl}}/auth/v1/token?grant_type=password
Content-Type: application/json
apikey: {{supabaseKey}}

{
  "email": "test@cloudbreak.app",
  "password": "motdepasse123"
}
