"""init peaks

Revision ID: b90b920dc145
Revises:
Create Date: 2026-03-20 14:16:27.948459

"""

from alembic import op
import sqlalchemy as sa
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "b90b920dc145"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peaks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_peaks_slug"), "peaks", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_peaks_slug"), table_name="peaks")
    op.drop_table("peaks")
    # ### end Alembic commands ###
