"""create terrain validations

Revision ID: c2078c6539a6
Revises: b4684d6c7d8d
Create Date: 2026-07-24 16:23:53.581581

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2078c6539a6"
down_revision: str | None = "b4684d6c7d8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terrain_validations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("prediction_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("result", sa.Boolean(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["prediction_id"], ["predictions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_terrain_validations_prediction_id",
        "terrain_validations",
        ["prediction_id"],
        unique=False,
    )
    op.create_index(
        "idx_terrain_validations_user_id", "terrain_validations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_terrain_validations_user_id", table_name="terrain_validations")
    op.drop_index("idx_terrain_validations_prediction_id", table_name="terrain_validations")
    op.drop_table("terrain_validations")
    # ### end Alembic commands ###
