class ApiError(Exception):
    """Erreur API dont le handler conserve le contrat de réponse direct."""

    def __init__(self, status_code: int, detail: str, code: str) -> None:
        self.status_code = status_code
        self.detail = detail
        self.code = code


class ErrorCode:
    NOT_FOUND = "NOT_FOUND"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    PEAK_NOT_FOUND = "PEAK_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    ALREADY_EXISTS = "ALREADY_EXISTS"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    WEATHER_UNAVAILABLE = "WEATHER_UNAVAILABLE"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
    SUBSCRIPTION_REQUIRED = "SUBSCRIPTION_REQUIRED"
    ACCOUNT_REQUIRED = "ACCOUNT_REQUIRED"
    INSTALLATION_ID_INVALID = "INSTALLATION_ID_INVALID"
    CLIENT_IP_UNAVAILABLE = "CLIENT_IP_UNAVAILABLE"
